# Taps
tap "homebrew/services"
tap "jesseduffield/lazydocker"

# Command-line tools
brew "ast-grep"
brew "bat"
brew "cmake", link: false
brew "cocoapods"
brew "colima"
brew "docker", link: false
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fisher"
brew "fnm"
brew "fzf"
brew "go"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "llvm"
brew "neovim"
brew "ninja"
brew "node"
brew "openjdk"
brew "pandoc"
brew "python@3.12"
brew "ripgrep"
brew "rustup"
brew "starship"
brew "swiftgen"
brew "swiftlint"
brew "tmux"
brew "tree"
brew "trivy"
brew "watchman"
brew "wget"
brew "xcodegen"
brew "yazi"
brew "zoxide"

# Applications
cask "android-studio"
cask "codex"
cask "docker-desktop"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "git-credential-manager"
cask "obsidian"
cask "zed"

# Global Node tools
npm "@earendil-works/pi-coding-agent"
npm "@github/copilot"
npm "@google/gemini-cli"
npm "pi-caveman"
npm "pnpm"
